"""Babs persistent-memory integration, SpliceCraft side.

The store ENGINE is bb_memory.py in the babs repo (tested there); here we cover the read/inject
helper the chat uses (`_babs_memory_index`, loaded into the system prompt) and the write shell-out
(`_babs_remember`, which delegates to bb_memory so the store logic has one owner). No real
subprocess or babs repo is required — the babs home + subprocess.run are monkeypatched."""
import subprocess
import types

import splicecraft as sc


def test_memory_index_empty_without_babs(monkeypatch):
    monkeypatch.setattr(sc, "_learn_resolve_babs_home", lambda: None)
    assert sc._babs_memory_index() == ""


def test_memory_index_reads_and_strips_generator_comment(tmp_path, monkeypatch):
    mem = tmp_path / "knowledge_base" / "memory"
    mem.mkdir(parents=True)
    (mem / "MEMORY.md").write_text(
        "# Babs memory\n<!-- generated by bb_memory.py -->\n- [Slash-free dates](d.md) — JUN 9 2026\n")
    monkeypatch.setattr(sc, "_learn_resolve_babs_home", lambda: tmp_path)
    idx = sc._babs_memory_index()
    assert "Slash-free dates" in idx and "JUN 9 2026" in idx
    assert "<!--" not in idx                         # the generator comment is stripped out


def test_memory_index_refuses_oversized_file(tmp_path, monkeypatch):
    mem = tmp_path / "knowledge_base" / "memory"
    mem.mkdir(parents=True)
    (mem / "MEMORY.md").write_text("- x\n" * 40000)   # >64 KB -> refuse to load (returns "")
    monkeypatch.setattr(sc, "_learn_resolve_babs_home", lambda: tmp_path)
    assert sc._babs_memory_index() == ""


def test_memory_index_char_capped(tmp_path, monkeypatch):
    mem = tmp_path / "knowledge_base" / "memory"
    mem.mkdir(parents=True)
    (mem / "MEMORY.md").write_text("- item\n" * 2000)   # <64 KB but many chars -> clipped to 4000
    monkeypatch.setattr(sc, "_learn_resolve_babs_home", lambda: tmp_path)
    assert len(sc._babs_memory_index()) <= 4000


def test_remember_returns_none_without_babs(monkeypatch):
    monkeypatch.setattr(sc, "_learn_resolve_babs_home", lambda: None)
    assert sc._babs_remember("a fact") is None


def test_remember_shells_bb_memory_and_returns_slug(tmp_path, monkeypatch):
    monkeypatch.setattr(sc, "_learn_resolve_babs_home", lambda: tmp_path)
    monkeypatch.setattr(sc, "_learn_babs_python", lambda h: "python3")
    captured = {}

    def fake_run(cmd, **kw):
        captured["cmd"] = cmd
        return types.SimpleNamespace(returncode=0, stdout="user-prefers-x\n", stderr="")

    monkeypatch.setattr(subprocess, "run", fake_run)
    slug = sc._babs_remember("user prefers x")
    assert slug == "user-prefers-x"
    assert "bb_memory.py" in captured["cmd"] and "remember" in captured["cmd"]
    assert any(a.startswith("--body=") for a in captured["cmd"])   # '=' form, leading-dash-safe


def test_remember_body_with_leading_dash_is_not_a_flag(tmp_path, monkeypatch):
    # a memory body that starts with '-' must not be mis-parsed by bb_memory's argparse as an option
    monkeypatch.setattr(sc, "_learn_resolve_babs_home", lambda: tmp_path)
    monkeypatch.setattr(sc, "_learn_babs_python", lambda h: "python3")
    captured = {}

    def fake_run(cmd, **kw):
        captured["cmd"] = cmd
        return types.SimpleNamespace(returncode=0, stdout="slug\n", stderr="")

    monkeypatch.setattr(subprocess, "run", fake_run)
    sc._babs_remember("-T7 is a strong promoter")
    body_arg = next(a for a in captured["cmd"] if a.startswith("--body="))
    assert body_arg == "--body=-T7 is a strong promoter"


def test_remember_returns_none_on_nonzero_exit(monkeypatch, tmp_path):
    monkeypatch.setattr(sc, "_learn_resolve_babs_home", lambda: tmp_path)
    monkeypatch.setattr(sc, "_learn_babs_python", lambda h: "python3")
    monkeypatch.setattr(subprocess, "run",
                        lambda cmd, **kw: types.SimpleNamespace(returncode=1, stdout="", stderr="boom"))
    assert sc._babs_remember("x") is None


def test_memory_index_survives_non_utf8(tmp_path, monkeypatch):
    # a MEMORY.md with a stray non-UTF-8 byte must not crash the chat turn this feeds every message —
    # it decodes with replacement rather than raising UnicodeDecodeError
    mem = tmp_path / "knowledge_base" / "memory"
    mem.mkdir(parents=True)
    (mem / "MEMORY.md").write_bytes(b"# Babs memory\n- valid line \xff\xfe still readable\n")
    monkeypatch.setattr(sc, "_learn_resolve_babs_home", lambda: tmp_path)
    idx = sc._babs_memory_index()
    assert isinstance(idx, str) and "valid line" in idx and "still readable" in idx
